name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/img_4.jpeg
  - assets/images/img_3.jpeg
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/images/test_1.png
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/images/ellipse_822.jpeg
  - assets/images/img_1.jpeg
  - assets/images/ellipse_8241.jpeg
  - assets/images/image.jpeg
  - assets/images/ellipse_824.jpeg
  - assets/images/ellipse_8242.jpeg
  - assets/images/mesh_gradient_3.jpeg
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/images/img_4.jpeg
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/images/img.jpeg
  - assets/images/ellipse_824.jpeg
  - assets/images/ellipse_8242.jpeg
  - assets/images/ellipse_822.jpeg
  - assets/images/test_4.png
  - assets/images/image.jpeg
  - assets/images/ellipse_8241.jpeg
  - assets/images/img_2.jpeg
  - assets/images/union.png
  - assets/images/img_1.jpeg
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/images/test_2.png
  - assets/images/test_3.png
  - assets/images/test_5.png
  - assets/images/test.png
  - assets/images/test_6.png
  - assets/images/screen_shot_20221013_at_2391.png
  - assets/images/img_3.jpeg
  - assets/images/img_4.jpeg
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown

